Arrowhead.POS/Controllers/AutoPolicyController.cs
using Arrowhead.POS.Core;
using Arrowhead.POS.Infrastructure;
using Arrowhead.POS.Model;
using Arrowhead.POS.Service;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Stripe;
using System.Net;
using System.Linq.Dynamic;
using RazorEngine.Templating;
using RazorEngine;
using Arrowhead.POS.Model.CCPaymentRequestModel;
using Arrowhead.POS.PaymentProcess;
using log4net;
using Arrowhead.POS.Process;
using System.Threading.Tasks;

namespace Arrowhead.POS.Controllers
{
    [RoutePrefix("auto")]
    public class AutoPolicyController : BaseController
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(AutoPolicyController));
        [Route("policy/{id}")]
        public ActionResult Index(long id = 0)
        {
            try
            {

                if (id > 0)
                {
                    ProjectSession.QuoteID = Convert.ToInt64(id);
                }

                // Add New Tab If Not Added In ProjectSession.TabDetail
                if (ProjectSession.QuoteID > 0)
                    CommonFunctions.AddNewTab(ProjectSession.QuoteID);


                AutoQuoteServices quoteServices = new AutoQuoteServices();
                GeneralServices generalServices = new GeneralServices();

                // Update Quote CurrentStep  Details
                CommonFunctions.UpdateCurrentQuoteStep(ProjectSession.QuoteID, Enums.QuoteOrderStatus.POLICY.ToString());



                QuoteRateResponseModel rateHistoryList = quoteServices.GetRateHistoryDetailsByQuoteID(ProjectSession.QuoteID);
                ViewBag.RateHistoryList = rateHistoryList;

                bool isQuoteCompleted = quoteServices.IsQuoteCompleted(ProjectSession.QuoteID);
                ViewBag.IsQuoteCompleted = isQuoteCompleted;
                AutoPolicyServices autopolicyServices = new AutoPolicyServices();
                var paymentDetails = autopolicyServices.GetPaymentByQuoteID(ProjectSession.QuoteID);
                var policyDetails = autopolicyServices.GetpolicyStatusDetails(ProjectSession.QuoteID);
                ViewBag.policyDetails = policyDetails;

                DateTime currentDate = ConvertTo.GetEstTimeNow();
                if (isQuoteCompleted == false)
                {
                    if (paymentDetails != null && paymentDetails.EffectiveDate != null)
                    {
                        if (paymentDetails.EffectiveDate.Value.Date < currentDate.Date)
                        {
                            if (quoteServices.UpdateEffectiveAndExpireDateByQuoteId(ProjectSession.QuoteID)) // if update then display message
                            {
                                this.ShowMessage(MessageExtension.MessageType.Error, "Effective date was updated to:" + currentDate.ToString("MM/dd/yyyy"));
                                CommonFunctions.UpdateQuoteToCoverageStep(ProjectSession.QuoteID, Enums.QuoteOrderStatus.COVERAGE.ToString());
                                return RedirectToAction("Index", "AutoCoverage", new { @id = ProjectSession.QuoteID });
                            }
                        }
                    }
                    if (rateHistoryList.DownPayment == 0)
                    {
                        generalServices.UpdateQuoteCurrentStep(ProjectSession.QuoteID, Enums.QuoteOrderStatus.COVERAGE.ToString());
                        return RedirectToAction("Index", "AutoCoverage", new { @id = ProjectSession.QuoteID });
                    }
                }

                return View(paymentDetails);
            }
            catch (Exception ex)
            {
                CommonFunctions.OnException(Enums.AuditHistoryModule.QP.ToString(), Enums.AuditHistoryOperation.V.ToString(), ex.ToString());
                this.ShowMessage(MessageExtension.MessageType.Error, ex.Message.ToString(), true);
            }

            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="payment"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("policy/{id?}")]
        public ActionResult SaveQuotesPayment(PaymentRequestModel payment)
        {
            try
            {
                //Log.Debug("SaveQuotesPayment request start :" + Newtonsoft.Json.JsonConvert.SerializeObject(payment));
                Log.Debug("SaveQuotesPayment request start :" + Newtonsoft.Json.JsonConvert.SerializeObject("Quote: " + payment.QuoteID + ", PaymentType: " + payment.PaymentMethodCode + ", Amount: " + payment.Amount));

                AutoPolicyServices autopolicyServices = new AutoPolicyServices();
                AutoQuoteServices autoQuoteServices = new AutoQuoteServices();
                GeneralServices generalServices = new GeneralServices();
                NSDServices nsdServices = new NSDServices();
                NSDContractModel _nsdContractModel = new NSDContractModel();
                decimal NSDAmount = 0;
                payment.UserId = ProjectSession.AgencyDetails.UserId;

                if (payment.PaymentMethodCode != Enums.PaymentMethod.CREDITCARD.ToString())
                {
                    payment.CCFees = 0;
                }

                // Manage Error handling for Declined CC 
                if (payment.TotalPremium == 0)
                {
                    var _payment = autopolicyServices.GetPaymentByQuoteID(payment.QuoteID);
                    payment.TotalPremium = _payment.TotalPremium;
                }

                var _downpayment = autopolicyServices.GetDownPaymentByQuoteId(payment.QuoteID);
                NSDAmount = autopolicyServices.GetNSDAmount(payment.QuoteID);
                payment.TotalNSD = NSDAmount;
                if ((payment.Amount) > (_downpayment + NSDAmount + payment.CCFees))
                {
                    autopolicyServices.UpdateAutoRateHistory(payment);
                }

                //payment.TotalCarrier = payment.Amount - payment.CCFees;

                payment.AgencyId = ProjectSession.AgencyDetails.AgencyId;
                var _custDetails = autoQuoteServices.GetPolicyHolderDetailById(payment.QuoteID);

                if (!string.IsNullOrEmpty(payment.PhoneNumber))
                {
                    payment.PhoneNumber = payment.PhoneNumber.ToPhoneNumber();
                }
                // Payment Reminder Update Applicant Contact if Applicant Contact / Payment Contact Not Matched
                if (_custDetails != null && !string.IsNullOrEmpty(_custDetails.ContactNo) && !string.IsNullOrEmpty(payment.PhoneNumber) && (_custDetails.ContactNo != payment.PhoneNumber))
                {
                    autoQuoteServices.UpdateQuoteContactDetails(payment.QuoteID, payment.PhoneNumber.ToPhoneNumber());
                }

                var _isNSDPlanSelected = autopolicyServices.IsNSDExists(payment.QuoteID);
                if (_isNSDPlanSelected)
                {
                    //NSDAmount = autopolicyServices.GetNSDAmount(payment.QuoteID);
                    payment.TotalCarrier = payment.Amount - NSDAmount - payment.CCFees;
                }
                else
                {
                    payment.TotalCarrier = payment.Amount - payment.CCFees;
                }

                string _Issuccess = Enums.PAYMENTSTATUS.SUCCESS.ToString();
                string errorMessage = string.Empty;
                string _PGCode = generalServices.GetActivePGCode();
                int _paymentGatewayMethodId = generalServices.GetActivePGID();

                PaymentProcess.TranzPayProcess tranzPayProcess = new PaymentProcess.TranzPayProcess();
                PaymentProcess.StripeProcess stripeProcess = new PaymentProcess.StripeProcess();
                PaymentProcess.AuthorizeProcess authorizeProcess = new PaymentProcess.AuthorizeProcess();

                if (payment.PaymentMethodCode == Enums.PaymentMethod.CREDITCARD.ToString())
                {
                    Log.Debug("SaveQuotesPayment CC Process start ");
                    payment.PaymentGatewayProviderId = _paymentGatewayMethodId; // set PaymentGatewayProviderId                

                    PaymentProcessRequestModel requestModel = new PaymentProcessRequestModel()
                    {
                        CarrierAmount = payment.TotalCarrier,
                        CCExpMonth = Convert.ToInt32(payment.PaymentMonth),
                        CCExpYear = Convert.ToInt32(payment.PaymentYear),
                        CCHolderName = payment.FullName,
                        CCNumber = payment.CardNumber.Replace("-", "").Replace("  ", "").Trim(),
                        CurrencyCode = "USA",
                        CustomerName = payment.FullName,
                        CVVNumber = payment.CVV,
                        QuoteID = payment.QuoteID,
                        TotalAmount = payment.Amount,
                        NSDAmount = payment.TotalNSD,
                        CustomerAddress1 = _custDetails.Address1,
                        CustomerAddress2 = _custDetails.Address2,
                        CustomerCity = _custDetails.City,
                        CustomerEmail = _custDetails.EmailId,
                        CustomerFirstName = _custDetails.FirstName,
                        CustomerLastName = _custDetails.LastName,
                        CustomerPhone = _custDetails.ContactNo,
                        CustomerState = _custDetails.StateAbbr,
                        CustomerZipcode = payment.ZipCode, // user entered zip code
                        Description = "Payment toward policy",
                        Token = payment.PGToken,
                        AgencyName = ProjectSession.AgencyDetails.AgencyName
                    };

                    if (_PGCode == Enums.PaymentGateway.STRIPE.ToString())
                    {

Arrowhead.POS/Views/AutoPolicy/Partial/_SendCustomerPaperwork.cshtml
@model Arrowhead.POS.Model.SendPaperWorkModel

<!-- Modal content-->
<div class="">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Send Customer PaperWork</h4>
    </div>

    <form action="@Url.Action("SendPaperWorkDetails", "AutoPolicy")" id="frmSendPaperwork" method="POST">
        <div class="modal-body" style="display: inline-block;">
            @Html.HiddenFor(model => model.QuoteId)

            <div class="col-sm-12 form-group">
                <div class="col-sm-3">
                    <label for="SendBy">Send By</label>
                </div>
                <div class="col-sm-6">
                    <div class="input-group">
                        <div id="radioBtn" class="btn-group radioBtn">
                            <label class="right attached ui button" style="border-radius:0 !important;">
                                <input type="radio" style="visibility:hidden;position: absolute;" name="SendTypeCode" id="isEmail" value="EMAIL" checked="checked"> Email
                            </label>
                            <label class="ui left attached button">
                                <input type="radio" style="visibility:hidden;position: absolute;" name="SendTypeCode" id="isFax" value="FAX"> Fax
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group  col-sm-12" id="dvEmail">
                <div class="col-sm-3">
                    <label>Email</label>
                </div>
                <div class="col-sm-6">
                    @Html.TextBoxFor(model => model.EmailId, new { @class = "form-control" })
                    @Html.ValidationMessageFor(f => f.EmailId)
                </div>
            </div>


            <div class="form-group  col-sm-12" id="dvEmailSubject">
                <div class="col-sm-3">
                    <label>Email Subject</label>
                </div>
                <div class="col-sm-6">
                    @Html.TextBoxFor(model => model.EmailSubject, new { @class = "form-control" })
                    @Html.ValidationMessageFor(f => f.EmailSubject)
                </div>
            </div>

            <div class="form-group  col-sm-12" id="dvFax">
                <div class="col-sm-3">
                    <label>Fax</label>
                </div>
                <div class="col-sm-6">
                    @Html.TextBoxFor(model => model.ContactNo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(f => f.ContactNo)
                </div>
            </div>

            <div class="form-group  col-sm-12">
                <div class="col-sm-3">
                    <label>Document Name</label>
                </div>
                <div class="col-sm-6">
                    @Html.TextBoxFor(model => model.DocumentName, new { @class = "form-control", @readonly = true })
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" id="btnSend" class="btn btn-sm btn-info mb10">Send</button>
            <button type="button" class="btn btn-sm mb10 btn-default" data-dismiss="modal">Close</button>
        </div>

    </form>

</div>


<script type="text/javascript">


    $(document).ready(function () {
        $("#dvFax").hide();

            $("#isEmail").parent().addClass('Checked');

            $('input[type=radio][name=SendTypeCode]').change(function () {
                $("#isEmail").parent().removeClass('Checked');
                $("#isFax").parent().removeClass('Checked');
                var value = $("input[name='SendTypeCode']:checked").val();
                if (value == 'EMAIL') {
                    $("#isEmail").parent().addClass('Checked');
                    $("#dvFax").hide();
                    $("#dvEmail").show();
                    $("#dvEmailSubject").show();

                }
                else if (value == 'FAX') {
                    $("#isFax").parent().addClass('Checked');
                    $("#dvFax").show();
                    $("#dvEmail").hide();
                    $("#dvEmailSubject").hide();
                }

            });

            $("#btnSend").click(function ()
            {
                $("body").CenterLoader(11001, "dvContainer");

                $.ajax({
                    url: '@Url.Action("SendPaperWorkDetails", "AutoPolicy")',
                    type: "POST",
                    data: { QuoteId: $("#QuoteId").val(), EmailId: $("#EmailId").val(), ContactNo: $("#ContactNo").val(), EmailSubject: $("#EmailSubject").val(), DocumentName: $("#DocumentName").val(), SendTypeCode: $("input[name='SendTypeCode']:checked").val()},
                    cache: false,
                    beforeSend: function () {
                    },
                    success: function (result)
                    {
                        $("#responsiveModel").modal('hide');
                        $("body").RemoveLoader();
                    },
                    complete: function () {
                    },
                    error: function (e) {
                        $("body").RemoveLoader();
                    }
                });
            });
        });
</script>

Arrowhead.POS/Views/AutoPolicy/Partial/_SendCustomerToSign.cshtml
@model Arrowhead.POS.Model.SendCustomerToSignModel

<!-- Modal content-->
<div class="">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Send to Customer to Sign</h4>
    </div>

    <form action="@Url.Action("SendDocusignLink", "AutoPolicy")" id="frmSendLink" method="POST">
        <div class="modal-body" style="display: inline-block;">
            @Html.HiddenFor(model => model.quoteID)

            @*<div class="col-sm-12">
            <label class="mt-radio">

                <input type="radio" name="MessageTypeCode" id="rbEMail" value="EMAIL" checked> Email
                <span></span>
            </label>
            &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <label class="mt-radio">

                <input type="radio" name="MessageTypeCode" id="rbText" value="TEXT"> Text Message
                <span></span>
            </label>
        </div>*@

            <div class="col-sm-12 form-group">
                <div class="col-sm-4">
                    <label for="SendBy">Send By</label>
                </div>
                <div class="col-sm-8 col-md-8 col-lg-6">
                    <div class="input-group">
                        <div id="radioBtn" class="btn-group radioBtn">
                            <label class="right attached ui button" style="border-radius:0 !important;">
                                <input type="radio" style="visibility:hidden;position: absolute;" name="MessageTypeCode" id="isTextMessage" value="TEXT" checked="checked"> Text Message
                            </label>
                            <label class="ui left attached button">
                                <input type="radio" style="visibility:hidden;position: absolute;" name="MessageTypeCode" id="isEmail" value="EMAIL"> Email
                            </label>
                        </div>
                    </div>
                </div>
            </div>

           @*class="col-sm-3 col-md-3 col-lg-2 control-label text-right"*@

            @*<div class="form-group col-sm-12">
            <div class="col-sm-3">
                <label>Customer Name</label>
            </div>
            <div class="col-sm-6">
                @Html.TextBoxFor(model => model.CustomerName, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.CustomerName)
            </div>
        </div>*@

            <div class="form-group  col-sm-12" id="dvEmail">
                <div class="col-sm-4">
                    <label>Email</label>
                </div>
                <div class="col-sm-6">
                    @Html.TextBoxFor(model => model.EmailID, new { @class = "form-control" })
                    @Html.ValidationMessageFor(f => f.EmailID)
                </div>
            </div>

            <div class="form-group  col-sm-12" id="dvPhoneNumber">
                <div class="col-sm-4">
                    <label>Phone Number</label>
                </div>
                <div class="col-sm-6">
                    @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(f => f.PhoneNumber)
                </div>
            </div>

            <div class="form-group  col-sm-12" id="">
                <div class="col-sm-4">
                    <label>URL</label>
                </div>
                <div class="col-sm-6">
                    @Html.TextBoxFor(model => model.URL, new { @class = "form-control" })
                    @Html.ValidationMessageFor(f => f.URL)
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" id="btnSend" class="btn btn-sm btn-info">Send</button>
            <button type="button" class="btn btn-sm mb10 btn-default" data-dismiss="modal">Close</button>
        </div>
    </form>
</div>



<script type="text/javascript">

    $(document).ready(function ()
    {
        $("#dvEmail").hide();

        $("#isTextMessage").parent().addClass('Checked');

        $('input[type=radio][name=MessageTypeCode]').change(function () {
            $("#isTextMessage").parent().removeClass('Checked');
            $("#isEmail").parent().removeClass('Checked');
            var value = $("input[name='MessageTypeCode']:checked").val()
            if (value == 'EMAIL') {
                $("#isEmail").parent().addClass('Checked');
                $("#dvPhoneNumber").hide();
                $("#dvEmail").show();
            }
            else if (value == 'TEXT') {
                $("#isTextMessage").parent().addClass('Checked');
                $("#dvPhoneNumber").show();
                $("#dvEmail").hide();
            }
        });

         $("#btnSend").click(function ()
            {
                $("body").CenterLoader(11001, "dvContainer");

                $.ajax({
                    url: '@Url.Action("SendDocusignLink", "AutoPolicy")',
                    type: "POST",
                    data: { quoteID: $("#quoteID").val(), EmailID: $("#EmailID").val(), PhoneNumber: $("#PhoneNumber").val(), URL: $("#URL").val(), MessageTypeCode: $("input[name='MessageTypeCode']:checked").val()},
                    cache: false,
                    beforeSend: function () {
                    },
                    success: function (result)
                    {
                        $("#responsiveModel").modal('hide');
                        $("body").RemoveLoader();
                    },
                    complete: function () {
                    },
                    error: function (e) {
                        $("body").RemoveLoader();
                    }
                });
            });
    });

</script>

Arrowhead.POS/Views/AutoPolicy/Partial/_VehicleListForIDCards.cshtml
@model List<Arrowhead.POS.Model.AutoVehicleModel>


<div class="">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Get ID Card</h4>
    </div>
    <div class="modal-body" style="display: inline-block;">
        @foreach (var item in Model)
        {
            <div Class="col-sm-12">
                <input type="checkbox" name="@item.AutoVehicleId" id="@item.AutoVehicleId" value="@item.AutoVehicleId"> @item.Year @item.Make @item.Model
                &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            </div>
        }
    </div>
    <div class="modal-footer">
        <button type="button" id="btnGetIDCards" class="btn btn-info btn-sm">Submit</button>
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
    </div>
</div>

<script type="text/javascript">
    $("#btnGetIDCards").click(function () {
       var URL = '@Url.Action("IDCard", "auto/policy")';
        $('input:checkbox').each(function () {
            var sThisVal = (this.checked ? $(this).val() : "");
            if (sThisVal != "") {
                var newWindow = window.open(URL + "/" + sThisVal, '_blank')
                if (newWindow != null && newWindow != 'undefined')
                {
                    newWindow.name = "ID Card";
                }
                  }
                });

     $('#responsiveModel').modal('toggle');
            });

</script>