Arrowhead.POS/Controllers/CustomerEsignController.cs
using Arrowhead.POS.Infrastructure;
using Arrowhead.POS.Service;
using Arrowhead.POS.Core;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Arrowhead.POS.Model;
using Microsoft.AspNet.SignalR;
using Arrowhead.POS.Hubs;
using RazorEngine.Templating;
using RazorEngine;
using System.IO;
using iTextSharp.text.pdf;
using Arrowhead.POS.Model.CCPaymentRequestModel;
using Arrowhead.POS.PaymentProcess;
using Arrowhead.POS.Process;
using System.Net;

namespace Arrowhead.POS.Controllers
{
    public class CustomerEsignController : Controller
    {
       
        [Route("~/customer-sign/view/{id}")]
        public ActionResult Index(string id)
        {
            int esignCustomerId = 2;
            long quoteId = Convert.ToInt64(CryptoGrapher.CBase64Decrypt(id));
            DocusignServices docusignServices = new DocusignServices();
            CommonServices commonServices = new CommonServices();
            var credentials = docusignServices.GetDocusignApiCredential();
            var quoteEnvelopes = docusignServices.GetEnvelopeById(quoteId);
            var DocusignQuoteModel = docusignServices.GetDocusignQuoteRecipientByQuoteId(quoteId);
            var cfi = DocusignConfiguration.DocusignConfigurations(credentials);
            EnvelopesApi envelopesApi = new EnvelopesApi(cfi);
            var hostUrl = commonServices.CheckHost(Request.Url.Host);
            string returnUrl = hostUrl + "/customer-signed/completed?qid=" + quoteId;
            RecipientViewRequest recipientViewRequest = new RecipientViewRequest();
            recipientViewRequest.ReturnUrl = returnUrl;
            recipientViewRequest.Email = DocusignQuoteModel.CustomerEmailId;
            recipientViewRequest.RecipientId = esignCustomerId.ToString();
            recipientViewRequest.AuthenticationMethod = Core.ConstantVariables.AuthenticationMethod;
            recipientViewRequest.UserName = DocusignQuoteModel.CustomerName;
            recipientViewRequest.ClientUserId = esignCustomerId.ToString();
            // create the recipient view (aka signing URL)
            ViewUrl recipientView = envelopesApi.CreateRecipientView(credentials.AccountId, quoteEnvelopes.EnvelopeId, recipientViewRequest);

            return Redirect(recipientView.Url);
        }

        //[Route("~/esign/thank-you")]
        [Route("~/customer-signed/completed")]
        public ActionResult CustomerSignedCompleted(long qid)
        {
            AutoPolicyServices autoPolicyServices = new AutoPolicyServices();
            CustomerDocumentServices customerDocumentServices = new CustomerDocumentServices();
            CommonServices commonServices = new CommonServices();
            AutoPolicyController autoPolicyController = new AutoPolicyController();
            NewPolicyModel _newPolicyModel = new NewPolicyModel();
            AutoQuoteServices autoQuoteServices = new AutoQuoteServices();
            PolicyBindResponseModel _policyBindRespModel = new PolicyBindResponseModel();
            string errorMessage = string.Empty;
            bool isError = false;
            string _Issuccess = Enums.PAYMENTSTATUS.SUCCESS.ToString();
            var quoteDetail = autoQuoteServices.GetQuoteInfo(qid);
            var paymentDetailModel = autoPolicyServices.GetPaymentDetailByQuoteId(qid);
            var paymentGatewayCode = autoPolicyServices.GetPaymentGatewayByQuoteId(qid);
            var hostUrl = commonServices.CheckHost(Request.Url.Host);

            if (Request.QueryString["event"] == "signing_complete")
            {
                GeneralServices generalServices = new GeneralServices();

                DocusignServices docusignServices = new DocusignServices();
                AuthorizeProcess _authorizeProcess = new AuthorizeProcess();

                Arrowhead.POS.Service.TemplateService templateServices = new Arrowhead.POS.Service.TemplateService();
                try
                {

                    // Capture Payment CC/ACH
                    if (paymentDetailModel != null && paymentDetailModel.PaymentMethodCd == Enums.PaymentMethod.CREDITCARD.ToString() &&
                        paymentGatewayCode == Enums.PaymentGateway.AUTHORIZENET.ToString() && paymentDetailModel.PaymentStatus == Enums.PAYMENTSTATUS.INITIATED.ToString() &&
                        string.IsNullOrWhiteSpace(quoteDetail.QuoteModel.PolicyNumber))
                    {
                        // Prepare PaymentReq Model
                        var paymentReqModel = autoPolicyServices.GetPaymentByQuoteID(qid);

                        PaymentProcessRequestModel requestModel = new PaymentProcessRequestModel()
                        {
                            CarrierAmount = paymentReqModel.TotalCarrier,
                            CurrencyCode = "USA",
                            CustomerName = paymentReqModel.FullName,
                            QuoteID = paymentReqModel.QuoteID,
                            TotalAmount = paymentReqModel.TotalAmount,
                            Description = "Payment toward policy",
                            Token = paymentReqModel.PgTransactionId
                        };

                        var _respProcess = _authorizeProcess.CapturePayment(requestModel);

                        PaymentResponseModel paymentResponseModel = new PaymentResponseModel();
                        paymentResponseModel.QuoteId = qid;
                        paymentResponseModel.ResponseFile = _respProcess.ResponseString;
                        autoPolicyServices.UpdatePaymentXMLAsync(paymentResponseModel);

                        _Issuccess = _respProcess.Status ? Enums.PAYMENTSTATUS.SUCCESS.ToString()
                            : Enums.PAYMENTSTATUS.FAIL.ToString();
                        errorMessage = _respProcess.StatusMessage;

                        if (string.IsNullOrEmpty(_respProcess.TransactionID) || _respProcess.TransactionID.ToString() == "0")
                        {
                            this.ShowMessage(MessageExtension.MessageType.Error, _respProcess.StatusMessage, true);
                        }

                        autoPolicyServices.UpdateQuotePaymentStatus(_respProcess, qid, _Issuccess);


                        
                    }
                    else if (paymentDetailModel != null)
                    {
                        _Issuccess = Enums.PAYMENTSTATUS.SUCCESS.ToString();
                    }
                    if (paymentDetailModel != null && _Issuccess.ToUpper() == Enums.PAYMENTSTATUS.SUCCESS.ToString())
                    {

                        var lstQuoteVehicles = docusignServices.UpdateQuoteEnvelopeStatusByQuoteID(qid);



                        if (string.IsNullOrWhiteSpace(quoteDetail.QuoteModel.PolicyNumber)) // if policy number not exist then only bind 
                        {
                            Arrowhead.POS.Process.Arrowhead arrowhead = new Arrowhead.POS.Process.Arrowhead();
                            RaterServices raterServices = new RaterServices();
                            var binderRequestModel = raterServices.PreparePolicyBindModel(qid, false);

                            
                            if (binderRequestModel.PaymentMethodCd == "CHECK")
                            {
                                if (hostUrl.Contains("arrowhead-pos-qa") || hostUrl.Contains("localhost"))
                                {
                                    QuoteEcheck quoteEcheck = autoPolicyServices.GetEcheckDetailsByQuotesId(binderRequestModel.QuoteID);
                                    binderRequestModel.IsNSDPlanSelected = autoPolicyServices.IsNSDExists(binderRequestModel.QuoteID);
                                    if (quoteEcheck != null && quoteEcheck.AccountNumber != null && quoteEcheck.RoutingNumber != null)
                                    {
                                        binderRequestModel.AccountNumber = quoteEcheck.AccountNumber;
                                        binderRequestModel.RoutingNumber = quoteEcheck.RoutingNumber;
                                    }
                                }
                            }

                            var policyModel = arrowhead.BindPolicy(binderRequestModel);
                            policyModel.QuoteID = qid;
                            docusignServices.UpdatePolicyNumber(policyModel, false);
                        }
                        else
                        {
                            if (!string.IsNullOrEmpty(quoteDetail.QuoteModel.PolicyNumber))
                            {
                                // Prepare Policy Bind Response model 
                                _policyBindRespModel = new PolicyBindResponseModel()
                                {
                                    IsSuccess = true,
                                    PolicyNumber = quoteDetail.QuoteModel.PolicyNumber,
                                    MessageDescription = quoteDetail.QuoteModel.PolicyMsgDesc,
                                    QuoteID = qid
                                };
                                docusignServices.UpdatePolicyNumber(_policyBindRespModel, false);
                            }
                        }

                        _newPolicyModel = autoPolicyServices.GetNewPolicyDetails(qid);




                        if (ConnectionList.MyConnectionList != null)
                        {
                            IHubContext _msgContext = GlobalHost.ConnectionManager.GetHubContext<NotificationHub>();
                            _msgContext.Clients.All.SignedCompleted(qid);
                        }

                        long customerSignTrackId = generalServices.GetGeneralStatusIdByType(Enums.GeneralStatus.SIGNMEDIUM.ToString(), Enums.SignMedium.CUSTOMERSIGN.ToString());

Arrowhead.POS/Views/CustomerEsign/Index.cshtml
@{
    ViewBag.Title = Arrowhead.POS.Infrastructure.ProjectSession.QuoteID + " - " + "Index";
    Layout = null;
}

Arrowhead.POS/Views/CustomerEsign/ThankYou.cshtml
@model Arrowhead.POS.Model.NewPolicyModel
@{
    ViewBag.Title = Model.VehicleIDCardModel[0].QuoteId + " - " + "Thank You";
    Layout = null;

}

<style>
    body {
        margin: 0;
        padding: 0;
        font-family: 'poppins';
        color: #353535;
        font-size: 14px;
    }

    .thanks-main {
        width: 600px;
        margin: 0 auto;
        padding: 20px;
        justify-content: space-between;
        align-items: center;
        background: #ffffff;
        border: 1px solid #ddd;
    }

    .thanks-verticle-center {
        min-height: 62vh;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
    }

    .thanks-main .main-title {
        /*font-size: 42px;
        line-height: 1.2;
        margin-bottom: 25px;*/
        font-size: 28px;
        color: #1e1246;
        font-weight: 500;
        padding-bottom: 20px;
        text-align: center;
        line-height: 1.1;
    }

    .download-link {
        font-weight: 500;
        padding-bottom: 5px;
        font-size: 20px;
        text-align: center;
    }

    .round-btn {
        background: #66bb6a;
        color: #ffffff;
        text-decoration: none;
        text-transform: uppercase;
        padding: 10px 20px;
        display: inline-block;
        border-radius: 7px;
        margin-top: 15px;
    }

    /*.download-link p {
        font-size: 20px;
        margin-top: 45px;
    }

    .download-link img {
        width: 190px;
        margin-top: 20px;
    }

    .download-link .round-btn {
        padding: 8px 30px !important;
        font-size: 20px !important;
        color: #1e1246;
        border: 2px solid #1e1246;
        border-radius: 30px;
        transition: 0.2s;
        cursor: pointer;
    }

    .fild-area [type="radio"]:checked + label, .fild-area button:hover {
        background-color: #1b728f;
        color: #ffffff;
    }

    .color-font {
        color: #1e1246 !important;
    }*/
</style>

@if (Model != null && Model.PolicyNumber!=null)
{
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,700&amp;display=swap" rel="stylesheet">

    <div class="thanks-main">
        <table style="width: 100%">
            <tbody>
                <tr><td><img style="width: 100%;" src="https://arrowheadpos.blob.core.windows.net/templates/new-policy.png"></td></tr>
            </tbody>
        </table>
        <table style="width: 100%;margin-top:20px; font-size: 14px; line-height: 1.6;">
            <tbody>
                @*<tr><td style="font-size: 20px;text-transform: uppercase;color: #66bb6a;font-weight: 500;">WELCOME TO ARROWHEAD,</td></tr>*@
                <tr><td style="font-weight: 500; ">Hi, @Model.FirstName @Model.LastName, thank you for your auto insurance purchase.  Please find your attached ID cards and signed application</td></tr>
                <tr><td style="padding-bottom: 5px;">Policy No: <b>@Model.PolicyNumber </b> </td></tr>
                <tr><td>Effective Date:  <b>@Model.EffectiveDate.ToString("MM/dd/yyyy")</b> </td></tr>
                <tr><td>Expiration Date: <b>@Model.ExpirationDate.ToString("MM/dd/yyyy")</b> </td></tr>

            </tbody>
        </table>

        @if (Model.SchedulePaymentModel.Count > 0)
        {
            <table width="100%" style="text-align: center; border-collapse: collapse;">
                <thead>
                    <tr>
                        <th style="font-size: 20px; text-transform: uppercase; width: 40%; border-bottom: 2px solid #ccc; padding-bottom: 5px; margin-bottom: 5px;">Payment No.</th>
                        <th style="font-size: 20px; text-transform: uppercase; width: 20%; border-bottom: 2px solid #ccc; padding-bottom: 5px; margin-bottom: 5px;">DUE DATE</th>
                        <th style="font-size: 20px; text-transform: uppercase; width: 20%; border-bottom: 2px solid #ccc; padding-bottom: 5px; margin-bottom: 5px;">Amount Due</th>
                    </tr>
                </thead>
                <tbody>
                    @{foreach (var item in Model.SchedulePaymentModel)
                    {
                            <tr>
                                <td style="padding: 5px 0;">@item.NumberOfPayments</td>
                                <td style="padding: 5px 0;">@item.DueDate.ToString("MM/dd/yyyy")</td>
                                <td style="padding: 5px 0;">$@item.MonthlyPayments</td>

                            </tr>
                        }
                    }
                </tbody>
            </table>
                        }
        <table style="width: 100%">
            <tbody>
                <tr><td>Your Agent's Information</td></tr>
                <tr><td>@Model.AgencyName</td></tr>
                <tr><td>@Model.AgencyPhone</td></tr>
            </tbody>
        </table>
        <table style="width: 100%">
            <tbody>
                @foreach (var idCard in Model.VehicleIDCardModel)
                {
                    <tr>
                        <td>
                            ID Card Vehicle @idCard.VehicleOrderId: <a href="#" id="IDCards" value="@idCard.AutoVehicleId">Download</a>
                        </td>
                    </tr>
                }
                <tr>
                    <td>
                        Signing Application: <a href="@Url.Action("ThankYouSignedApplication", "CustomerEsign", new { qid = Model.VehicleIDCardModel[0].QuoteId  })">Download</a>
                    </td>
                </tr>
            </tbody>
        </table>
        @*<table style="width: 100%;margin: 10px 0; font-size: 14px; line-height: 1.6;">
                <tbody>
                    <tr><td class="main-title">Thank You For <br>Connecting With Us</td></tr>
                    <tr><td class="download-link">We will get back to you shortly.</td></tr>
                    <tr><td></td></tr>
                    <tr><td style="text-align: center;"><a class="round-btn" href="https://www.arrowheadgrp.com/">Back to home</a></td></tr>
                </tbody>
            </table>*@

    </div>
    }
    else
    {
        <div style="font-size:large;align-items:center;color:red;">
            @Html.RenderMessages()
        </div>
    }
@*<div class="inner-container row m-0 px-4">
        <div class="thanks-main thanks-verticle-center">
            <h1 class="main-title color-font">Thank You For <br>Connecting With Us</h1>
            <div class="download-link">
                <img src="~/Assets/images/happiness1.svg">
                <p>We will get back to you shortly.</p>
                <div class="fild-area"><button class="round-btn" onclick="window.location.href = 'https://www.arrowheadgrp.com/';">Back to home</button></div>
            </div>
        </div>
    </div>*@

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function ()
    {
         $('a[id="IDCards"]').click(function ()
            {
                var URL = '@Url.Action("IDCard", "auto/policy")';
                var vehicleValue = $(this).attr("value");
                var newWindow = window.open(URL + "/" + vehicleValue, '_blank')
                newWindow.name = "ID Card";
            });


    })
</script>