Arrowhead.POS/Controllers/AutoCoverageController.cs
using Arrowhead.POS.Core;
using Arrowhead.POS.Infrastructure;
using Arrowhead.POS.Model;
using Arrowhead.POS.Service;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using RazorEngine;
using RazorEngine.Templating;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;

namespace Arrowhead.POS.Controllers
{
    [RoutePrefix("auto")]
    public class AutoCoverageController : BaseController
    {
        // GET: AutoCoverage
        [Route("coverage/{id?}")]
        public ActionResult Index(long? id = 0)
        {
            if (id > 0)
            {
                ProjectSession.QuoteID = Convert.ToInt64(id);
            }

            // Add New Tab If Not Added In ProjectSession.TabDetail
            if (ProjectSession.QuoteID > 0)
                CommonFunctions.AddNewTab(ProjectSession.QuoteID);

            AutoCoverageServices coverageServices = new AutoCoverageServices();
            GeneralServices generalServices = new GeneralServices();
            var coverageList = coverageServices.GetQuoteCoverages(ProjectSession.QuoteID);
            if (coverageList.Count > 0)
                TempData["headerTitle"] = "Coverage Options";



            // Update Quote CurrentStep  Details
            CommonFunctions.UpdateCurrentQuoteStep(ProjectSession.QuoteID, Enums.QuoteOrderStatus.COVERAGE.ToString());

            return View(coverageList);
        }

        /// <summary>
        /// Save Coverages To DB
        /// </summary>
        /// <param name="coverage">Coverage list Json String</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SaveCoverageDetails(string coverage)
        {
            var rateResponseModel = new List<QuoteRateResponseModel>();
            GeneralServices _generalServices = new GeneralServices();
            AutoCoverageServices coverageServices = new AutoCoverageServices();
            AutoQuoteServices _autoQuoteServices = new AutoQuoteServices();
            List<VerifyLienholderModel> lienholderModel = null;
            long quoteStatusId = _generalServices.GetGeneralStatusIdByType(Enums.GeneralStatus.QUOTETYPE.ToString(), Enums.QuoteType.QUOTE.ToString());
            try
            {


                TempData["headerTitle"] = "Payment Plan";

                var quoteCoverage = JsonConvert.DeserializeObject<List<Model.StateCoveragesModel>>(coverage);
               
                coverageServices.InsertQuoteCoverage(quoteCoverage, ProjectSession.QuoteID);
                lienholderModel = coverageServices.isLienHolderExist(ProjectSession.QuoteID);
                lienholderModel = lienholderModel.Where(w => w.IsLeinComCollVerified == false).ToList();
                if (lienholderModel != null && lienholderModel.Count > 0)
                {
                    return PartialView("~/Views/AutoCoverage/Partial/_DisplayMissingCoverages.cshtml", lienholderModel);
                }
                else
                {
                    rateResponseModel = GetRateResponse();
                    // Check Quick Quote and Rates Exist
                    if (_autoQuoteServices.IsQuickQuoteByQuoteId(ProjectSession.QuoteID) && _autoQuoteServices.IsQuoteRatesExist(ProjectSession.QuoteID))
                    {
                        _autoQuoteServices.UpdateQuoteTypeByQuoteId(ProjectSession.QuoteID, quoteStatusId);
                    }
                }

            }
            catch (Exception ex)
            {
                CommonFunctions.OnException(Enums.AuditHistoryModule.COV.ToString(), Enums.AuditHistoryOperation.I.ToString(), ex.ToString());

                var err = ex.ToString();
            }
            return PartialView("~/Views/AutoCoverage/Partial/_PayPlans.cshtml", rateResponseModel);
        }

        /// <summary>
        /// Update Purchase Initiated When Click on Buy Now
        /// </summary>
        /// <param name="rateID">RateHistory ID</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult UpdatePurchaseInitiated(int rateID, int planID)
        {
            var rateResponseModel = new List<QuoteRateResponseModel>();
            AutoQuoteServices quotesServices = new AutoQuoteServices();
            NSDServices nsdServices = new NSDServices();
            decimal nsdPrice = 0;

            try
            {
                if (!quotesServices.IsGarrageAddressMissing(ProjectSession.QuoteID))
                {
                    return Json(new { IsError = true, IsException = false }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    if (planID > 0)
                    {
                        nsdPrice = nsdServices.SaveAutoQuoteNsdPlan(ProjectSession.QuoteID, planID, ProjectSession.AgencyDetails.UserId);
                    }

                    if (rateID > 0)
                    {
                        quotesServices.UpdatePurchaseInitiated(rateID, ProjectSession.QuoteID, nsdPrice, ProjectSession.AgencyDetails.UserId);
                    }
                    return Json(new { IsError = false, IsException = false }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                CommonFunctions.OnException(Enums.AuditHistoryModule.COV.ToString(), Enums.AuditHistoryOperation.S.ToString(), ex.ToString());

                var err = ex.ToString();
                return Json(new { IsError = true, IsException = true }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="quoteId"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult PrintQuote(long quoteId, long rateID)
        {
            CommonServices commonServices = new CommonServices();
            GeneralServices generalServices = new GeneralServices();
            Arrowhead.POS.Service.TemplateService templateService = new Arrowhead.POS.Service.TemplateService();
            string printQuoteDetails = string.Empty;
            try
            {
                TemplateModel template = templateService.GetTemplateDetails(Enums.TemplateType.PRINTQUOTE.ToString());
                if (ProjectSession.QuoteID > 0)
                    printQuoteDetails = GetPrintQuoteTemplate(ProjectSession.QuoteID, rateID, template);
                else
                    printQuoteDetails = GetPrintQuoteTemplate(quoteId, rateID, template);

                return Json(new { PrinQuoteHTML = printQuoteDetails, QuoteId = (ProjectSession.QuoteID > 0 ? ProjectSession.QuoteID : quoteId) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return null;
            }
        }



        /// <summary>
        /// Download Pdf File from JSON String
        /// </summary>
        /// <param name="GridHtml"></param>
        /// <returns></returns>
        public FileResult PdfFile(string jsonStr)
        {
            PolicyStatusModel _policyStatusModel = null;
            string[] jsonDetails = null;
            try
            {
                using (MemoryStream stream = new System.IO.MemoryStream())
                {
                    string strDelimitor = "$$$";
                    if (jsonStr.Contains(strDelimitor)) // quick quote 
                    {
                        jsonDetails = jsonStr.Split(new[] { strDelimitor }, StringSplitOptions.None); // split html string and quote id 

                        StringReader sr = new StringReader(jsonDetails[0]);
                        AutoPolicyServices autoPolicyServices = new AutoPolicyServices();
                        Document pdfDoc = new Document(PageSize.A4, 40f, 0f, 20f, 0f);
                        PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                        pdfDoc.Open();
                        XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                        pdfDoc.Close();
                        _policyStatusModel = autoPolicyServices.GetpolicyStatusDetails(Convert.ToInt32(jsonDetails[1]));
                    }
                    else
                    {
                        StringReader sr = new StringReader(jsonStr);
                        AutoPolicyServices autoPolicyServices = new AutoPolicyServices();
                        Document pdfDoc = new Document(PageSize.A4, 40f, 0f, 20f, 0f);
                        PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                        pdfDoc.Open();
                        XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                        pdfDoc.Close();
                        _policyStatusModel = autoPolicyServices.GetpolicyStatusDetails(ProjectSession.QuoteID);
                    }
                    string fileName = " Auto Quote" + " " + "#" + (ProjectSession.QuoteID > 0 ? ProjectSession.QuoteID : Convert.ToInt32(jsonDetails[1])) + " " + _policyStatusModel.FirstName + " " + _policyStatusModel.LastName + ".pdf";
                    return File(stream.ToArray(), "application/pdf", fileName);
                }
            }
            catch (Exception ex)
            {
                return null;
            }
        }



        /// <summary>
        /// 
        /// </summary>
        /// <param name="quoteId"></param>
        /// <param name="templateModel"></param>
        /// <returns></returns>
        public string GetPrintQuoteTemplate(long quoteId, long rateId, TemplateModel templateModel)
        {
            TemplateModel _template = templateModel;
            Arrowhead.POS.Service.TemplateService templateServices = new Arrowhead.POS.Service.TemplateService();
            AutoPolicyServices autoPolicyServices = new AutoPolicyServices();
            CommonServices commonServices = new CommonServices();

Arrowhead.POS/Views/AutoDriver/AddDriver.cshtml
@model Arrowhead.POS.Model.AutoDriverModel
@{
    ViewBag.Title = Arrowhead.POS.Infrastructure.ProjectSession.QuoteID + " - " + "Add Driver";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<div id="dvManageDriver">
    @Html.Partial("~/Views/AutoDriver/Partial/_ManageDriver.cshtml", Model)
</div>*@

<div>
    <div class="panel container panel-primary" style="width:95%; margin:0px 0px 0px 15px;">
        <div id="dvManageDriver">
            @Html.Partial("~/Views/AutoDriver/Partial/_ManageDriver.cshtml", Model)
        </div>
    </div>
</div>

Arrowhead.POS/Views/AutoDriver/EditDriver.cshtml
@model Arrowhead.POS.Model.AutoDriverModel

@{
    ViewBag.Title = Arrowhead.POS.Infrastructure.ProjectSession.QuoteID + " - " + "Edit Driver";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="dvManageVehicle">
    @Html.Partial("~/Views/AutoDriver/Partial/_ManageDriver.cshtml", Model)
</div>

Arrowhead.POS/Views/AutoDriver/Index.cshtml
@model List<Arrowhead.POS.Model.AutoDriverModel>

@{
    ViewBag.Title = Arrowhead.POS.Infrastructure.ProjectSession.QuoteID + " - " + "Driver Options";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var driverId = TempData["driverId"] != null ? TempData["driverId"] : 0;
    Arrowhead.POS.Service.AutoDriverServices autoDriverServices = new Arrowhead.POS.Service.AutoDriverServices();
    var firstDriverId = autoDriverServices.GetDefaultDriverID(Arrowhead.POS.Infrastructure.ProjectSession.QuoteID);
    var isAddedNewDriver = TempData["IsAddNewDriver"] != null ? TempData["IsAddNewDriver"] : false;
}


<div class="panel panel-default">
    <div class="panel-heading main_title driver-opt-title">
        <span>Driver Options</span>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#driverOption" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <div class="container row driverDiv">
        <div class="tabing_navigatiin">

            <div id="driverOption" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
                <ul class="pull-left header_left_menu" id="dvTabBar">
                    @foreach (var item in Model)
                    {
                        <li driver-id="@item.AutoDriverId" class="new_menu active firstAddbtn">
                            <a href="javascript:;"> @item.FirstName @item.LastName</a>
                        </li>
                    }
                    @if (ViewBag.DriverCount >= 0)
                    {
                        if (ViewBag.DriverCount < 8 && ViewBag.paymentCompleted == false)
                        {
                            <li driver-id="0" class="new_menu active firstTab">
                                <a href="javascript:;"> Add Driver<i class="fa fa-plus"></i></a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div>
        <div class="panel container panel-primary" style="width:95%; margin:0px 0px 0px 15px;">
            <div class="divDriverInfo">
            </div>
        </div>
    </div>


    @*<div class="panel-body">
            <div class="row">
                @if (ViewBag.DriverCount > 0)
                {
                    if (ViewBag.DriverCount < 8)
                    {
                        <div class="col-sm-4 col-md-4 col-lg-2 mb10">
                            <button type="button" class="btn btn-info btn-lg" id="btnAddDriver">ADD DRIVER <i class="fa fa-plus" aria-hidden="true"></i></button>
                        </div>
                    }
                    <div class="col-sm-4 col-md-4 col-lg-2">
                        <a href="@Url.Action("Index", "AutoCoverage" , new { id = Arrowhead.POS.Infrastructure.ProjectSession.QuoteID })" class="btn btn-info btn-lg green_button">CONTINUE TO COVERAGES <i class="fa fa-long-arrow-right" aria-hidden="true"></i></a>
                    </div>
                }
                else
                {
                    <div class="col-sm-4 col-md-4 col-lg-2 mb10">
                        <button type="button" class="btn btn-info btn-lg" id="btnAddDriver">ADD DRIVER <i class="fa fa-plus" aria-hidden="true"></i></button>
                    </div>
                }
            </div>
        </div>*@
</div>
<script type="text/javascript">

    $(document).ready(function ()
    {
        var vehicleCount = @ViewBag.DriverCount;

        if ('@ViewBag.paymentCompleted' == 'False')
        {
            if ('@driverId' != 0 && '@driverId.ToString()' != '') {
                var val = '@driverId.ToString()';
                setTimeout(function () { $("li[driver-id='" + val + "']").click() }, 10);
            } else {
                $(function ()
                {
                    if ('@ViewBag.DriverCount' < 8)
                    {
                        if ('@isAddedNewDriver' == 'False' && '@firstDriverId' > 0) // Edit Driver Active First Driver
                        {
                            $("li[driver-id='" + @firstDriverId + "']").click()
                        }
                        else
                        {
                            addNewDriverPage('@Arrowhead.POS.Infrastructure.ProjectSession.QuoteID')
                        }
                    }
                    else {
                        setTimeout(function () { $('.firstAddbtn').first().click() }, 10);
                    }
                });
            }
        }
        else {
            setTimeout(function () { $('.firstAddbtn').first().click() }, 10);
        }



        $('.firstTab').click(function() {
        addNewDriverPage('@Arrowhead.POS.Infrastructure.ProjectSession.QuoteID');
    })

        $(".firstAddbtn").click(function() {
            $(".divDriverInfo").CenterLoader(11001);
            $(this).siblings().removeClass('active');
            $('[driver-id="0"]').removeClass('active');
            $(this).addClass('active')
            var driver = $(this).attr('driver-id');
        var quote = '@Arrowhead.POS.Infrastructure.ProjectSession.QuoteID';
        console.log("button click : ", driver)
            if (driver > 0)
        {
            $.ajax({
                url: '@Url.Action("EditDriverDetailTab", "AutoDriver")',
                type: "POST",
                data:
                {
                    qid: quote,
                    id: driver
                },
                success: function(result) {
                    $('.divDriverInfo').html('');
                    $('.divDriverInfo').html(result);
                    $(".divDriverInfo").RemoveLoader();
                    driver = "";
                },
                error: function(e) {
                    console.log("Error : ", e);
                }
            });
        }
    });

});

    function addNewDriverPage(quote) {
        $(".divDriverInfo").CenterLoader(11001);
        $('[driver-id="0"]').addClass('active');
        $('.firstAddbtn').removeClass('active');

        $.ajax({
        @*url: '@Url.Action("driver/add", "auto")' + '/' + quote,*@
            url: "@Url.Action("AddDriverDetail", "AutoDriver")",
                type: "POST",
                data: {
                    id: quote
                },
            success: function (result) {
                    $('.divDriverInfo').html('');
                    $('.divDriverInfo').html(result);
                    $(".divDriverInfo").RemoveLoader();
                    driver = "";
                },
                error: function (e) {
                    console.log("Error : ", e);
                }
            });
    }
    @*$("#btnAddDriver").click(function () {
        window.location.href ='@Url.Action("AddDriverDetail", "AutoDriver", new { id = Arrowhead.POS.Infrastructure.ProjectSession.QuoteID })';
    });*@

</script>